# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge

# Java
java.version=25

# Minecraft
minecraft_version=26.3
min_minecraft_version=26.3

# Mappings
deps.parchment=

# Fabric
deps.fabric_loader=0.19.5
deps.fabric_api=0.161.0
deps.fabric_gametest_api=4.0.21+4a7fa0819e

# NeoForge
deps.neoforge=26.3.0.7-beta

# Dependencies
deps.yacl=3.9.7+26.3
deps.mod_menu=21.0.0-beta.1
deps.catalogue=
deps.global_datapacks=
deps.global_packs=26.2.1
deps.open_loader=
deps.terra=
